apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-a
  labels:
    dashboards: grafana-a
    folders: grafana-a
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      admin_password: start
      admin_user: root
  deployment:
    spec:
      template:
        spec:
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                  claimName: grafana-a-pvc
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  route:
    spec:
      host: delfos-grafana-test.apps.delfos-dev.e5y1.p2.openshiftapps.com
      path: /